#
# Build GMT and run tests
#
name: Tests
on:
  push:
    # build master and 6.x branches
    branches:
      - master
      - 6.[0-9]+
      - github-actions  # TODO: remove this before merging
  pull_request:
  # schedule daily tests
  schedule:
    - cron: '0 12 * * *'

jobs:
  linux:
    name: 'Linux'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
